    version: "3.9"
    services:
      postgres:
        image: postgres:latest
        container_name: postgres
        hostname: postgres
        ports:
          - 4112:5432
        environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: swiggy
        volumes:
          - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
      pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        depends_on:
          - postgres
        ports:
          - "5555:80"
        environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
          - pgadmin-data:/var/lib/pgadmin
        restart: unless-stopped

    volumes:
      postgres-data:
      pgadmin-data: